/* tslint:disable */
/* eslint-disable */
/**
 * Preferences API
 * API for config server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof Entry
     */
    value?: any | null;
}
/**
 * 
 * @export
 * @interface GlobalEntryPydanticWithOverride
 */
export interface GlobalEntryPydanticWithOverride {
    /**
     * 
     * @type {string}
     * @memberof GlobalEntryPydanticWithOverride
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof GlobalEntryPydanticWithOverride
     */
    value?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof GlobalEntryPydanticWithOverride
     */
    overrideFull?: boolean;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface PublicEntry
 */
export interface PublicEntry {
    /**
     * 
     * @type {string}
     * @memberof PublicEntry
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof PublicEntry
     */
    value?: any | null;
}
/**
 * 
 * @export
 * @interface PublicEntryPydanticWithOverride
 */
export interface PublicEntryPydanticWithOverride {
    /**
     * 
     * @type {string}
     * @memberof PublicEntryPydanticWithOverride
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof PublicEntryPydanticWithOverride
     */
    value?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof PublicEntryPydanticWithOverride
     */
    overrideFull?: boolean;
}
/**
 * 
 * @export
 * @interface UserEntryBatchGet
 */
export interface UserEntryBatchGet {
    /**
     * 
     * @type {string}
     * @memberof UserEntryBatchGet
     */
    key: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserEntryBatchGet
     */
    userIds: Array<number>;
}
/**
 * 
 * @export
 * @interface UserEntryPydantic
 */
export interface UserEntryPydantic {
    /**
     * 
     * @type {string}
     * @memberof UserEntryPydantic
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof UserEntryPydantic
     */
    value?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserEntryPydantic
     */
    userId: number;
}
/**
 * 
 * @export
 * @interface UserEntryPydanticWithOverride
 */
export interface UserEntryPydanticWithOverride {
    /**
     * 
     * @type {string}
     * @memberof UserEntryPydanticWithOverride
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof UserEntryPydanticWithOverride
     */
    value?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserEntryPydanticWithOverride
     */
    userId: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntryPydanticWithOverride
     */
    overrideFull?: boolean;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationError
     */
    loc: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    type: string;
}

/**
 * PreferencesApi - axios parameter creator
 * @export
 */
export const PreferencesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes global config preferences associated with provided key
         * @summary Del Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelGlobalPref: async (key: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesDelGlobalPref', 'key', key)
            const localVarPath = `/userprefs/api/v1/preferences/global`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes public config preferences associated with provided key
         * @summary Del Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelPublicPref: async (key: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesDelPublicPref', 'key', key)
            const localVarPath = `/userprefs/api/v1/preferences/public`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Del User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelUserPref: async (key: string, userId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesDelUserPref', 'key', key)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('apiV1PreferencesDelUserPref', 'userId', userId)
            const localVarPath = `/userprefs/api/v1/preferences/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get global config preference associated with provided key.
         * @summary Get Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetGlobalPref: async (key: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesGetGlobalPref', 'key', key)
            const localVarPath = `/userprefs/api/v1/preferences/global`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get public config preference associated with provided key.
         * @summary Get Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetPublicPref: async (key: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesGetPublicPref', 'key', key)
            const localVarPath = `/userprefs/api/v1/preferences/public`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetUserPref: async (key: string, userId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('apiV1PreferencesGetUserPref', 'key', key)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('apiV1PreferencesGetUserPref', 'userId', userId)
            const localVarPath = `/userprefs/api/v1/preferences/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref Batch
         * @param {UserEntryBatchGet} userEntryBatchGet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetUserPrefBatch: async (userEntryBatchGet: UserEntryBatchGet, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userEntryBatchGet' is not null or undefined
            assertParamExists('apiV1PreferencesGetUserPrefBatch', 'userEntryBatchGet', userEntryBatchGet)
            const localVarPath = `/userprefs/api/v1/preferences/batchuser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userEntryBatchGet, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stores global preferance in global config database
         * @summary Set Global Pref
         * @param {GlobalEntryPydanticWithOverride} globalEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetGlobalPref: async (globalEntryPydanticWithOverride: GlobalEntryPydanticWithOverride, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'globalEntryPydanticWithOverride' is not null or undefined
            assertParamExists('apiV1PreferencesSetGlobalPref', 'globalEntryPydanticWithOverride', globalEntryPydanticWithOverride)
            const localVarPath = `/userprefs/api/v1/preferences/global`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(globalEntryPydanticWithOverride, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stores public preferance in public config database
         * @summary Set Public Pref
         * @param {PublicEntryPydanticWithOverride} publicEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetPublicPref: async (publicEntryPydanticWithOverride: PublicEntryPydanticWithOverride, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'publicEntryPydanticWithOverride' is not null or undefined
            assertParamExists('apiV1PreferencesSetPublicPref', 'publicEntryPydanticWithOverride', publicEntryPydanticWithOverride)
            const localVarPath = `/userprefs/api/v1/preferences/public`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(publicEntryPydanticWithOverride, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stores user preferance in user config database  User want to write to VACATIONREQUEST on user_id=3 1. User have to have privilege userprefs_user_writeself_VACATIONREQUEST and has to be logged as user_id=3 2. User have to have privilege userprefs_user_write_VACATIONREQUEST_ROLEX and user_id=3 must be in role ROLEX
         * @summary Set User Pref
         * @param {UserEntryPydanticWithOverride} userEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetUserPref: async (userEntryPydanticWithOverride: UserEntryPydanticWithOverride, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userEntryPydanticWithOverride' is not null or undefined
            assertParamExists('apiV1PreferencesSetUserPref', 'userEntryPydanticWithOverride', userEntryPydanticWithOverride)
            const localVarPath = `/userprefs/api/v1/preferences/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userEntryPydanticWithOverride, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PreferencesApi - functional programming interface
 * @export
 */
export const PreferencesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PreferencesApiAxiosParamCreator(configuration)
    return {
        /**
         * Deletes global config preferences associated with provided key
         * @summary Del Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesDelGlobalPref(key: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesDelGlobalPref(key, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Deletes public config preferences associated with provided key
         * @summary Del Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesDelPublicPref(key: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesDelPublicPref(key, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Del User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesDelUserPref(key: string, userId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesDelUserPref(key, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get global config preference associated with provided key.
         * @summary Get Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesGetGlobalPref(key: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Entry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesGetGlobalPref(key, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get public config preference associated with provided key.
         * @summary Get Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesGetPublicPref(key: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesGetPublicPref(key, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesGetUserPref(key: string, userId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserEntryPydantic>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesGetUserPref(key, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref Batch
         * @param {UserEntryBatchGet} userEntryBatchGet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesGetUserPrefBatch(userEntryBatchGet: UserEntryBatchGet, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEntryPydantic>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesGetUserPrefBatch(userEntryBatchGet, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Stores global preferance in global config database
         * @summary Set Global Pref
         * @param {GlobalEntryPydanticWithOverride} globalEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride: GlobalEntryPydanticWithOverride, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Stores public preferance in public config database
         * @summary Set Public Pref
         * @param {PublicEntryPydanticWithOverride} publicEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride: PublicEntryPydanticWithOverride, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Stores user preferance in user config database  User want to write to VACATIONREQUEST on user_id=3 1. User have to have privilege userprefs_user_writeself_VACATIONREQUEST and has to be logged as user_id=3 2. User have to have privilege userprefs_user_write_VACATIONREQUEST_ROLEX and user_id=3 must be in role ROLEX
         * @summary Set User Pref
         * @param {UserEntryPydanticWithOverride} userEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PreferencesSetUserPref(userEntryPydanticWithOverride: UserEntryPydanticWithOverride, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PreferencesSetUserPref(userEntryPydanticWithOverride, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PreferencesApi - factory interface
 * @export
 */
export const PreferencesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PreferencesApiFp(configuration)
    return {
        /**
         * Deletes global config preferences associated with provided key
         * @summary Del Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelGlobalPref(key: string, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesDelGlobalPref(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes public config preferences associated with provided key
         * @summary Del Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelPublicPref(key: string, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesDelPublicPref(key, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Del User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesDelUserPref(key: string, userId: number, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesDelUserPref(key, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get global config preference associated with provided key.
         * @summary Get Global Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetGlobalPref(key: string, options?: any): AxiosPromise<Entry> {
            return localVarFp.apiV1PreferencesGetGlobalPref(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Get public config preference associated with provided key.
         * @summary Get Public Pref
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetPublicPref(key: string, options?: any): AxiosPromise<PublicEntry> {
            return localVarFp.apiV1PreferencesGetPublicPref(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref
         * @param {string} key 
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetUserPref(key: string, userId: number, options?: any): AxiosPromise<UserEntryPydantic> {
            return localVarFp.apiV1PreferencesGetUserPref(key, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user config preference associated with provided key.
         * @summary Get User Pref Batch
         * @param {UserEntryBatchGet} userEntryBatchGet 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesGetUserPrefBatch(userEntryBatchGet: UserEntryBatchGet, options?: any): AxiosPromise<Array<UserEntryPydantic>> {
            return localVarFp.apiV1PreferencesGetUserPrefBatch(userEntryBatchGet, options).then((request) => request(axios, basePath));
        },
        /**
         * Stores global preferance in global config database
         * @summary Set Global Pref
         * @param {GlobalEntryPydanticWithOverride} globalEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride: GlobalEntryPydanticWithOverride, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride, options).then((request) => request(axios, basePath));
        },
        /**
         * Stores public preferance in public config database
         * @summary Set Public Pref
         * @param {PublicEntryPydanticWithOverride} publicEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride: PublicEntryPydanticWithOverride, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride, options).then((request) => request(axios, basePath));
        },
        /**
         * Stores user preferance in user config database  User want to write to VACATIONREQUEST on user_id=3 1. User have to have privilege userprefs_user_writeself_VACATIONREQUEST and has to be logged as user_id=3 2. User have to have privilege userprefs_user_write_VACATIONREQUEST_ROLEX and user_id=3 must be in role ROLEX
         * @summary Set User Pref
         * @param {UserEntryPydanticWithOverride} userEntryPydanticWithOverride 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PreferencesSetUserPref(userEntryPydanticWithOverride: UserEntryPydanticWithOverride, options?: any): AxiosPromise<any> {
            return localVarFp.apiV1PreferencesSetUserPref(userEntryPydanticWithOverride, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PreferencesApi - object-oriented interface
 * @export
 * @class PreferencesApi
 * @extends {BaseAPI}
 */
export class PreferencesApi extends BaseAPI {
    /**
     * Deletes global config preferences associated with provided key
     * @summary Del Global Pref
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesDelGlobalPref(key: string, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesDelGlobalPref(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes public config preferences associated with provided key
     * @summary Del Public Pref
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesDelPublicPref(key: string, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesDelPublicPref(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Del User Pref
     * @param {string} key 
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesDelUserPref(key: string, userId: number, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesDelUserPref(key, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get global config preference associated with provided key.
     * @summary Get Global Pref
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesGetGlobalPref(key: string, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesGetGlobalPref(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get public config preference associated with provided key.
     * @summary Get Public Pref
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesGetPublicPref(key: string, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesGetPublicPref(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get user config preference associated with provided key.
     * @summary Get User Pref
     * @param {string} key 
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesGetUserPref(key: string, userId: number, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesGetUserPref(key, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get user config preference associated with provided key.
     * @summary Get User Pref Batch
     * @param {UserEntryBatchGet} userEntryBatchGet 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesGetUserPrefBatch(userEntryBatchGet: UserEntryBatchGet, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesGetUserPrefBatch(userEntryBatchGet, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stores global preferance in global config database
     * @summary Set Global Pref
     * @param {GlobalEntryPydanticWithOverride} globalEntryPydanticWithOverride 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride: GlobalEntryPydanticWithOverride, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesSetGlobalPref(globalEntryPydanticWithOverride, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stores public preferance in public config database
     * @summary Set Public Pref
     * @param {PublicEntryPydanticWithOverride} publicEntryPydanticWithOverride 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride: PublicEntryPydanticWithOverride, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesSetPublicPref(publicEntryPydanticWithOverride, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stores user preferance in user config database  User want to write to VACATIONREQUEST on user_id=3 1. User have to have privilege userprefs_user_writeself_VACATIONREQUEST and has to be logged as user_id=3 2. User have to have privilege userprefs_user_write_VACATIONREQUEST_ROLEX and user_id=3 must be in role ROLEX
     * @summary Set User Pref
     * @param {UserEntryPydanticWithOverride} userEntryPydanticWithOverride 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApi
     */
    public apiV1PreferencesSetUserPref(userEntryPydanticWithOverride: UserEntryPydanticWithOverride, options?: any) {
        return PreferencesApiFp(this.configuration).apiV1PreferencesSetUserPref(userEntryPydanticWithOverride, options).then((request) => request(this.axios, this.basePath));
    }
}


